あるレベル帯の曲の難易度は全て同じだと仮定する。新曲が追加されたときに、自分がその曲をプレイするとどれぐらいの得点が取れそうか知りたい。というのも、音楽ゲームは100円で3曲プレイできるが、得点によっては次の曲に進めない制約があるからである。100円でより多くの曲をプレイするためには、リスクを取りたくない。得点を確率分布に落とし込むことで、このリスクを定量評価できる。

### 仮定
- 同じレベル帯の曲は同じ難易度である。(同じレベルなら曲$_i$のスコアの分布$X_i$は全て同じ分布)
- プレイヤーのスキルは上昇しないものとする。

以下の同じレベル帯で考えることにする。

- プレイごとに得られるスコアは独立同分布である。

#### 知りたい
曲を一回プレイしたときに獲得するスコアXの分布$f^{(X)}(x)$

#### 知っている
曲$_i$を$n_i$回プレイしたときの最大のスコア$m_i$

### ノーテーション
ここで議論する曲の背景に存在する難易度は同じと仮定する。

曲が1〜Nまであるとする。

$n_i$...曲$_i$をプレイした回数

曲を一回プレイしてスコアを得ることを1回の試行とする。

$X_{(i,j)}$...曲$_i$をプレイした中でj回目に出たスコア。

過去の全ての試行を確率変数として表すと以下のようになる。

| 曲  | 過去の全ての試行 |
| :-------------: | :-------------: |
| 1  |  $X_{(1,1)}$,$X_{(1,2)}$,...,$X_{(1,n_{1})}$ |
| 2  | $X_{(2,1)}$,$X_{(2,2)}$,...,$X_{(2,n_{2})}$  |
| ...  | ...  |
| N  | $X_{(N,1)}$,$X_{(N,2)}$,...,$X_{(N,n_{N})}$  |

これらは全て独立同分布に従うと仮定する。またその分布に従う確率変数を$X$と代表して書くことにする。
 
$X$...ある曲を一回プレイしたときに得られるスコアの確率変数。

$f^{(X)}(x)$...推定したい$X$の従う確率分布。

今手元にあるデータは

| 曲  | ベストスコア | プレイ回数 |
| :-------------: | :-------------: | :-----------: |
| 1  |  max($X_{(1,1)}$,$X_{(1,2)}$,...,$X_{(1,n_{1})}$) | $n_1$ |
| 2  | max($X_{(2,1)}$,$X_{(2,2)}$,...,$X_{(2,n_{2})}$)  | $n_2$ |
| ...  | ...  | ... |
| N  | max($X_{(N,1)}$,$X_{(N,2)}$,...,$X_{(N,n_{N})}$)  | $n_N$ |


ベストスコアは確率変数の最大値なのでこれも確率変数である。
$$M_{n_i}=max(X_{(i,1)},X_{(i,2)},...,X_{(i,n_{i})})$$
と定義すると、表は以下のようにスッキリとした見た目になる。

| 曲  | ベストスコア | プレイ回数 |
| :-------------: | :-------------: | :-----------: |
| 1  |$M_{n_i}$| $n_1$ |
| 2  |$M_{n_2}$| $n_2$ |
| ...  | ...  | ... |
| N  |$M_{n_N}$| $n_N$ |


$M_n$...n回試行したときの最大値の確率変数。

$f^{(M_n)}(m)$...$M_n$の従う確率密度関数。

もう一度、目的を確認しておこう。ベストスコアとプレイ回数のデータから、曲を一回プレイしたときに得られる得点$X$の確率分布を求めたいというのが目的である。

### 式
$f^{(X)}(x)$を$f^{(M_n)}(m)$から推定したい。ここで$f^{(X)}(x)$はパラメーター$\boldsymbol\theta$によって表現できるものとする。
そのため$f^{(X)}(x ; \boldsymbol\theta)$と書くことにする。$f^{(X)}(x ; \boldsymbol\theta)$を求めるとはこのパラメーター$\boldsymbol\theta$を求めることである。
$\boldsymbol\theta$を求めるために以下の手続きを取る。


1. $f^{(X)}(x; \boldsymbol\theta)$を使って,最大値の分布$f^{(M_n)}(m ; \boldsymbol\theta)$を構築する。(ここで示した$\boldsymbol\theta$は$f^{(X)}(x ; \boldsymbol\theta)$のパラメーターに共通)
2. $f^{(M_n)}(m ; \boldsymbol\theta)$の負の対数尤度関数を構築する。
3. 2を損失関数とみなし、最小となるパラメーター$\boldsymbol\theta$を探す。ここでは$X$に分布を仮定して具体的な計算式にまで落とし込む。


これらについて一つ一つ式変形をしていこう。



#### 1について
確率密度関数$f(\cdot)$に対して累積密度関数を$F(\cdot)$と書くことにする。$P(\cdot)$を$\cdot$に記載された条件を満たす確率と定義する。このとき、最大値の分布を考えてみる。
最大値の分布は以下の式から議論をスタートしよう。

$$P(M_n < m)  = \left(P(X < m)\right)^n $$

これは、｢最大値の確率変数$M$が$m$より小さい確率は、全ての$X$が$m$より小さい確率と一致する｣という内容を記述する式である。これを累積分布関数に書き換えれば、

$$ F^{(M_n)}(m) = \left(F^{(X)}(m)\right)^n $$

となる。

したがって、$f^{(M_n)}(m)$は以下のように表せる。

$$ f^{(M_n)}(m) = \frac{d}{dm}F^{(M_n)}(m) $$

$$ f^{(M_n)}(m) = \frac{d}{dm}\left(F^{(X)}(m)\right)^n $$

$$ f^{(M_n)}(m) = n \left(F^{(X)}(m)\right)^{n-1}\frac{d}{dm}\left(F^{(X)}(m)\right) $$

$$ f^{(M_n)}(m) = n \left(F^{(X)}(m)\right)^{n-1}f^{(X)}(m)  $$

式の形を少し整理して、パラメーター$\boldsymbol\theta$を自明に書くと以下になる。

$$ f^{(M_n)}(m ; \boldsymbol\theta) = n f^{(X)}(m;\boldsymbol\theta) \left(F^{(X)}(m;\boldsymbol\theta)\right)^{n-1} $$

#### 2について
N個の曲について、プレイした回数とベストスコアはわかっている。これについて負の対数尤度関数を構築することを考える。

$$\text{負の対数尤度} = -\ln\left(\prod_i^N f^{(M_{n_i})}(m_i ; \boldsymbol\theta)\right)$$

となる。1の結果を代入し形を整えると以下のようになる。

$$\text{負の対数尤度} = -\sum_i^N \ln\left( f^{(M_{n_i})}(m_i ; \boldsymbol\theta)\right)$$

$$\text{負の対数尤度} = -\sum_i^N \ln\left( n_i f^{(X)}(m_i;\boldsymbol\theta) \left(F^{(X)}(m_i;\boldsymbol\theta)\right)^{n_i-1} \right)$$

$$\text{負の対数尤度} = -\sum_i^N \left[ \ln n_i + \ln f^{(X)}(m_i;\boldsymbol\theta) + (n_i-1)\ln \left(F^{(X)}(m_i;\boldsymbol\theta)\right) \right]$$




#### 3について
2で求めた負の対数尤度をもとに、$\boldsymbol\theta$についての損失関数を定義すると、
$$loss(\boldsymbol\theta)=-\sum_i^N \left[ \ln f^{(X)}(m_i;\boldsymbol\theta) + (n_i-1)\ln \left(F^{(X)}(m_i;\boldsymbol\theta)\right) \right]$$
となる。

これは見ての通り、$X$についての分布$f^{(X)}(m_i;\boldsymbol\theta)$を仮定しないと損失が計算できない形式になっている。

そこで、今回は$f^{(X)}(m_i;\boldsymbol\theta)$にベータ分布を仮定した。これは、5年間プレイしてきての経験と、実際にランダムに選曲してスコアを実測した結果から来る仮定である。(実測のヒストグラムは付録に示す)

つまり
$$f^{(X)}(x;\boldsymbol\theta)=\frac{x^{a-1}(1-x)^{b-1}}{B(a,b)}(=Beta(x; a,b))$$
である。ただし、$B(\cdot)$はベータ関数で、
$$B(a,b)=\int_0^1 x^{a-1}(1-x)^{b-1} dx$$
である。

これを先の損失関数に代入すると、
$$loss(a,b)=-\sum_i^N \left[ \ln \frac{m_i^{a-1}(1-m_i)^{b-1}}{B(a,b)} + (n_i-1)\ln \int_0^{m_i} \frac{m_i^{a-1}(1-m_i)^{b-1}}{B(a,b)} dm_i \right]$$


$$loss(a,b)=-\sum_i^N \left[ -\ln B(a,b) + \ln (m_i^{a-1}(1-m_i)^{b-1}) + (n_i-1)\ln \int_0^{m_i} \frac{m_i^{a-1}(1-m_i)^{b-1}}{B(a,b)} dm_i \right]$$

$$loss(a,b)=-\sum_i^N \left[ -\ln B(a,b) + (a-1)\ln m_i + (b-1)\ln(1-m_i) + (n_i-1)\ln \int_0^{m_i} \frac{m_i^{a-1}(1-m_i)^{b-1}}{B(a,b)} dm_i \right]$$

シグマの中の第4項目の積分は正則化された不完全ベータ関数と言われるものである。表記を簡単にするために、
$$I_x(a,b) = \int_0^{x} \frac{x^{a-1}(1-x)^{b-1}}{B(a,b)} dx$$
とおくと、損失関数は結局

$$loss(a,b)=-\sum_i^N \left[ -\ln B(a,b) + (a-1)\ln m_i + (b-1)\ln(1-m_i) + (n_i-1)\ln I_x(a,b) \right]$$

$$loss(a,b)=\sum_i^N \left[ \ln B(a,b) - (a-1)\ln m_i - (b-1)\ln(1-m_i) - (n_i-1)\ln I_x(a,b) \right]$$

となる。

ゴールは、
$$a,b = \arg \min_{a,b} loss(a,b)$$
を求めることである。

ここではa,bをグリッド状に全探索することで、損失関数を最小化するパラメーターを探索する。

In [25]:
from scipy.special import betaln, betainc, beta
import numpy as np

In [17]:
def loss(a,b,ns:np.array,ms:np.array):
    firstitem=ns+lnbeta_a_b
    seconditem=-(a-1)*np.log(ms)
    thirditem=-(b-1)*np.log(1-ms)
    fourthitem=-(ns-1)*np.log(betainc(a,b,ms))
    
    
    return None

In [27]:
betainc(1,2,np.array([0.1,0.2,1])) #これ普通の不完全ベータ関数ではなくて正規化された不完全ベータ関数じゃん

array([0.19, 0.36, 1.  ])

In [26]:
beta(1,2)

0.5

In [23]:
np.e**betaln(1,2)

0.5

In [1]:
import torch

In [2]:
import torch.functional as func
import pyro.distributions as dist

In [3]:
hoge=dist.Beta(2,3)

In [5]:
hoge.icdf(0.3)

NotImplementedError: 

In [53]:
hoge.cdf(9)

NotImplementedError: 

In [18]:
torch.FloatTensor([0.3])

tensor([0.3000])

$$\psi(x) = \frac{d}{dx} \ln\left(\Gamma\left(x\right)\right) = \frac{\Gamma'(x)}{\Gamma(x)}$$

In [40]:
#実装ではベータ関数はガンマ関数から自分で実装する必要がありそう。

In [12]:
torch.lgamma(torch.Tensor([10]))

tensor([12.8018])

In [ ]:
k

$$loss(a,b)=-\sum_i^N \left[ -n_i\ln B(a,b) + \ln (m_i^{a-1}(1-m_i)^{b-1}) + (n_i-1)\ln \int_0^{m_i} m_i^{a-1}(1-m_i)^{b-1} dm_i \right]$$

$$loss(a,b)=-\sum_i^N \left[ -n_i\ln B(a,b) + (a-1)\ln m_i + (b-1)\ln(1-m_i) + (n_i-1)\ln \int_0^{m_i} m_i^{a-1}(1-m_i)^{b-1} dm_i \right]$$

シグマの中の第4項の積分は不完全ベータ関数である。簡単のために
$$B_x(a,b)\int_0^{x} x^{a-1}(1-x)^{b-1} dx$$
と記号を定義すると、損失関数は、

$$loss(a,b)=-\sum_i^N \left[ -n_i\ln B(a,b) + (a-1)\ln m_i + (b-1)\ln(1-m_i) + (n_i-1)\ln B_{m_i}(a,b) \right]$$

$$loss(a,b)=\sum_i^N \left[ +n_i\ln B(a,b) - (a-1)\ln m_i - (b-1)\ln(1-m_i) - (n_i-1)\ln B_{m_i}(a,b) \right]$$


となる。

ゴールは、
$$a,b = \arg \min_{a,b} loss(a,b)$$
を求めることである。

ここではa,bをグリッド状に全探索することで、損失関数を最小化するパラメーターを探索する。