In [1]:
import numpy as np

In [2]:
competition_table=np.array([
    [  0,203,239,213],
    [ 53,  0,127,131],
    [ 28,108,  0,116],
    [ 37, 95,120,  0]
])

In [3]:
competition_table

array([[  0, 203, 239, 213],
       [ 53,   0, 127, 131],
       [ 28, 108,   0, 116],
       [ 37,  95, 120,   0]])

In [4]:
competition_table.T+competition_table

array([[  0, 256, 267, 250],
       [256,   0, 235, 226],
       [267, 235,   0, 236],
       [250, 226, 236,   0]])

In [5]:
theta=np.array([1,2,3,4])
theta.reshape(1,-1)+ theta.reshape(-1,1)

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [6]:
def ret_bt_parames(n_iter,competition_table):
    assert competition_table.shape[0] == competition_table.shape[1]
    n_team=competition_table.shape[0]
    
    theta=np.ones(n_team) / n_team #this is the bt model's parameters

    n_battle_in_competition_table=competition_table+competition_table.T
    n_wins=competition_table.sum(axis=1)
    
    for iloop in range(n_iter):
        acc=(n_battle_in_competition_table/(theta.reshape(1,-1)+ theta.reshape(-1,1))).sum(axis=1)
        t=n_wins/acc
        theta = t/t.sum()
        
    return theta

In [7]:
ret_bt_parames(100,competition_table)

array([0.6481719 , 0.14189358, 0.10338365, 0.10655086])